add_newline = true

format = '''[╭─](#d10475) ❄️ $username$hostname$directory$git_branch$git_commit$git_state$git_status$jobs$cmd_duration$python$conda$nodejs$direnv$docker
[╰─](#d10475) $character'''

# right_format = '$time'

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'
# success_symbol = '😸'
# error_symbol = '😿'

[shell]
disabled = false
format = '$indicator'
fish_indicator = '🐟 '
bash_indicator = '[BASH](bright-white) '
zsh_indicator = '[ZSH](bright-white) '

[username]
disabled = false
show_always = true
format =  '[$user]($style)'
style_user = 'bold #00c8ff'
style_root = 'bold #ff006a'

[hostname]
format = '[@](bold fg:#f9e2af)[${hostname}]($style) '
disabled = false
style = 'bold #ff006a'
ssh_only = false

[git_branch]
only_attached = true
format = '[$symbol$branch]($style) '
symbol = ''
style = 'bold bright-yellow bold'

[git_commit]
only_detached = true
format = '[ﰖ$hash]($style) '
style = 'bold bright-yellow bold'

[git_state]
style = 'bold bright-purple bold'

[git_status]
style = 'bold bright-green bold'

[directory]
disabled = false
format = '📁[$path]($style)[$read_only]($read_only_style) '
style = 'bold fg:#75aeff'
use_os_path_sep = true
read_only = ' 🔒'
truncation_length = 0
truncate_to_repo = false

[cmd_duration]
disabled = false
format = '[$duration]($style) '
style = 'bright-blue'

[time]
disabled = false
use_12hr = true
format = '[$time]($style) 🕙'
style = '#00ffc3'

[jobs]
disabled = false
style = 'bright-green bold'

[python]
disabled = false
symbol = '󰌠 '
format = '[\[${symbol}\(${virtualenv}\)\]]($style)'
style = 'yellow bold'

[conda]
disabled = false
symbol = '🐍 '
format = '[\[${symbol}\(${environment}\)\]]($style)'
style = 'bold fg:#81bff2'

[nodejs]
disabled = false
symbol = ' '
format = '[\[${symbol}\(${environment}\)\]]($style)'
style = 'bold fg:#34eb98'

[direnv]
disabled = false
symbol = ' '
format = '[\[${symbol}\(${loaded}/${allowed}\)\]]($style)'
style = 'bold fg:#34eb98'

[docker_context]
disabled = false
symbol = '🐳 '
format = '[\[${symbol}\(${context}\)\]]($style)'
style = 'bold fg:#346beb'